import { Router } from "express";

import { getIngredientStockHistoryHandler, getOrderWeekStats,getRevenueByPizzaHandler,getRevenuePerDay,getTop5Pizzas } from "./stats-handlers";
import { isAuthenticated } from "@/api/auth/auth-middleware";

const router = Router();

router.get("/orders/week", isAuthenticated, getOrderWeekStats);

router.get("/ingredients/:id/stockHistory", isAuthenticated, getIngredientStockHistoryHandler);

router.get("/pizzas/top", isAuthenticated, getTop5Pizzas);
router.get("/pizzas/revenue", isAuthenticated, getRevenuePerDay);
router.get("/pizzas/revenueByPizza", isAuthenticated, getRevenueByPizzaHandler);


export default router;
// 1. Order Statistics
//   Total Orders: The total number of orders placed.
//   Orders Per Day/Week/Month: The number of orders placed per day, week, or month.
//   Revenue Per Day/Week/Month: The total revenue generated per day, week, or month.
//   Average Order Value: The average value of an order.
//   Top Selling Pizzas: The most frequently ordered pizzas.
//   Order Status Distribution: The distribution of orders by status (e.g., pending, completed, canceled).
// 2. Ingredient Statistics
//   Ingredient Stock Levels: Current stock levels of each ingredient.
//   Low Stock Alerts: Ingredients that are below a certain stock threshold.
//   Ingredient Usage: The quantity of each ingredient used over a period of time.
//   Ingredient Cost: The total cost of ingredients used.
// 3. Customer Statistics
//   Total Customers: The total number of customers.
//   New Customers: The number of new customers acquired over a period of time.
//   Customer Retention Rate: The percentage of returning customers.
//   Top Customers: Customers who have placed the most orders or spent the most money.
// 4. Pizza Statistics
//   Pizza Popularity: The number of times each pizza has been ordered.
//   Revenue by Pizza: The total revenue generated by each pizza.
//   Pizza Ingredient Cost: The cost of ingredients for each pizza.